import json
print("3-odam malumotlari")
with open('d_json.json','r') as a:
    name=json.load(a)
print(name[1])
with open('d_json.json','r') as b:
    name=json.load(b)
print(name[2]['_id'])
print(name[2]['index'])
print(name[2]['guid'])
print(name[2]['picture'])
print(name[2]['eyeColor'])
print(name[2]['company'])
print(name[2]['email'])
print(name[2]['address'])
print(name[2]['about'])
print(name[2]['registered'])
print(name[2]['isActive'])
print(name[2]['balance'])
print(name[2]['age'])
print(name[2]['name'])
print(name[2]['gender'])
print(name[2]['phone'])
print(name[2]['tags'])
print(name[2]['tags'][2])
print(name[2]['tags'][3])
